### ISSUE TITLE
Internal server error when using OpenNMT-tf

### ISSUE THREAD

**Issue by anasir-ureed** [aws/sagemaker-python-sdk#1057]
Reference: 0411850995

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow , OpenNMT-tf
- **Framework Version**: 1.14
- **Python Version**: py3
- **CPU or GPU**: GPU
- **Python SDK Version**: latest
- **Are you using a custom image**: script training

### Describe the problem
I am using OpenNMT-tf for training. When the training reaches the export step, the exported model is not exported properly, and a strange error named "Internal server error" appears. 

### Minimal repro / logs
Unfortunately, there is nothing in the logs telling anything about the issue! 

- **Exact command to reproduce**:
```
estimator = TensorFlow(entry_point=local_training_script_path,
                       dependencies=['model.py'],
                       train_instance_type='ml.p3.2xlarge',
                       train_instance_count=1,
                       checkpoint_s3_uri=checkpoint_path,
                       output_path=model_artifacts_location,
                       code_location=custom_code_upload_location,
                       role=sagemaker.get_execution_role(),
                       framework_version='1.14',
                       py_version='py3',
                       script_mode=True,
                       train_use_spot_instances=train_use_spot_instances,
                       train_max_run=train_max_run,
                       train_max_wait=train_max_wait,
                       train_volume_size=75)
estimator.fit(training_inputs_location, job_name=job_name_sagemaker, wait=True)
```
The shell script contains

```
pip install OpenNMT-tf
onmt-main ...
```

Please advise,

**Comment by mvsusp** [comment]
Hello @anasir-ureed 

Please share with us a minimal code example, allowing us to reproduce the issue.

Thanks for using SageMaker

**Comment by anasir-ureed** [comment]
Hello @mvsusp 

Thanks for your reply

This is the script I am using in the entry point. "train.sh"

```
#!/bin/bash
pip install OpenNMT-tf
onmt-main train_and_eval --model_type NMTMedium --config ${SM_CHANNEL_TRAINING}/config/exp1.yml --data_dir ${SM_CHANNEL_TRAINING} --run_dir /opt/ml/checkpoints/
cp -R /opt/ml/checkpoints/* ${SM_MODEL_DIR}/

```

In the config file, 

```
model_dir: .

data:
  train_features_file: data/train.sp.en
  train_labels_file: data/train.sp.ar
  eval_features_file: data/val.sp.en
  eval_labels_file: data/val.sp.ar
  source_words_vocabulary: data/t.vocab
  target_words_vocabulary: data/t.vocab

params:
  optimizer: GradientDescentOptimizer
  learning_rate: 0.5
  param_init: 0.1
  clip_gradients: 5.0
  decay_type: exponential_decay
  decay_rate: 0.8
  decay_steps: 50000
  start_decay_steps: 50000
  min_learning_rate: 0.0001
  beam_width: 5
  maximum_iterations: 250
  replace_unknown_target: true

train:
  batch_size: 128
  bucket_width: 5
  save_checkpoints_steps: 300
  save_summary_steps: 50
  train_steps: 250000
  maximum_features_length: 300
  maximum_labels_length: 300
  keep_checkpoint_max: 10
  average_last_checkpoints: 8

eval:
  eval_delay: 7200
  batch_size: 8
  external_evaluators: BLEU
  exporters: last
  save_eval_predictions: true

infer:
  batch_size: 32
  n_best: 1
```

In the notebook please use 

```
train_use_spot_instances = False # the issue happens in spot and on demand
train_max_run=3600 * 24 * 5
train_max_wait = 3600 * 24 * 5 if train_use_spot_instances else None

estimator = TensorFlow(entry_point="train.sh",
                       train_instance_type='ml.p3.2xlarge',
                       train_instance_count=1,
                       checkpoint_s3_uri=checkpoint_path, # Any location you wish
                       role=sagemaker.get_execution_role(),
                       framework_version='1.14',
                       py_version='py3',
                       script_mode=True,
                       train_use_spot_instances=train_use_spot_instances,
                       train_max_run=train_max_run,
                       train_max_wait=train_max_wait,
                       train_volume_size=75)
estimator.fit(training_inputs_location,  wait=True) 
```

In training_inputs_location, the directory structure is as following:
```
config/exp1.yml
data/train.sp.en
data/train.sp.ar
data/val.sp.en
data/val.sp.ar
data/t.vocab
data/t.vocab
```

Best wishes,
