### ISSUE TITLE
sagemaker.get_execution_role() returns incorrect ARN

### ISSUE THREAD

**Issue by hughack** [aws/sagemaker-python-sdk#2089]
**Describe the bug**
I manually created an execution role for SageMaker Studio called `AmazonSageMaker-ExecutionRole-ap-southeast-2`

Calling `sagemaker.get_execution_role()` within a SageMaker Studio Notebook returns the incorrect role ARN:

```
arn:aws:iam::************:role/service-role/AmazonSageMaker-ExecutionRole-ap-southeast-2
```

Actual ARN:

```
arn:aws:iam::************:role/AmazonSageMaker-ExecutionRole-ap-southeast-2
```

**To reproduce**
Create role in CloudFormation:
```yaml
  SageMakerExecutionRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: !Sub AmazonSageMaker-ExecutionRole-${AWS::Region}
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - sagemaker.amazonaws.com
                  - ecs-tasks.amazonaws.com
              Action:
                - "sts:AssumeRole"
        Path: /
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
          - !Ref SageMakerExecutionPolicy
```

Setup SageMaker Studio with this role as execution role.

Open a notebook and run:

```python
from sagemaker import get_execution_role
print(get_execution_role())
```

**Expected behavior**
Output role ARN:
```
arn:aws:iam::************:role/AmazonSageMaker-ExecutionRole-ap-southeast-2
```
Actual output:
```
arn:aws:iam::************:role/service-role/AmazonSageMaker-ExecutionRole-ap-southeast-2
```

Note addition of `service-role/`.

**Additional context**
Looks like this line is the culprit:

https://github.com/aws/sagemaker-python-sdk/blob/1fdefe06068e5eaf9f63287737d55db96ecc12cf/src/sagemaker/session.py#L3501
