### ISSUE TITLE
Bug with the sagemaker.get_execution_role() 

### ISSUE THREAD

**Issue by szamarin** [aws/sagemaker-python-sdk#2186]
**Describe the bug**
When using get_execution_role() in SageMaker Studio with a non generated IAM role, the method does not return the correct ARN unless the role name contains "AmazonSageMaker-ExecutionRole" and is placed into the "/service-role/" path. These are hard coded into the get_caller_identity_arn() method of sagemaker session. This becomes an issue when deploying the role with CloudFormation. The logical id can not contain dashes, so when I create a role like this:
```
SageMakerExecutionRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - sagemaker.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /service-role/
```
The method will fail to include /service-role/ in the arn. I have to explicitly specify the RoleName, or place the role into the root path. 

**To reproduce**
Create a sagemaker execution role without including "AmazonSageMaker-ExecutionRole" in its name and place that role under the "/service-role/" path. Assign the role to a SageMaker Studio domain or user profile. Run sagemaker.get_execution_role() in a Studio notebook. The returned arn will not include "service-role" in the path.

**Expected behavior**
get_execution_role() should always return the correct arn
